# Generated by Django 4.1.5 on 2023-01-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_point_pointusing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointusing',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
