# Generated by Django 4.1.5 on 2023-01-23 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pointusing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointusing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
