# Generated by Django 4.1.5 on 2023-01-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_pointusing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='point',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
