# Generated by Django 4.0.3 on 2023-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
